dist: trusty
sudo: false
language: go
go:
- "1.x"
- master

before_script:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1
- go get -u golang.org/x/lint/golint

script:
- make test
- make fmtcheck
- make vet

matrix:
  fast_finish: true
  allow_failures:
  - go: master

before_deploy:
- make targets
